language: php

php:
  - 5.6
  - 7.0
  - hhvm

install:
  - travis_retry composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - mkdir -p build/logs
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

script:
  - ./vendor/bin/kahlan --clover=build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
